Description: >
  Update Cloudfront distribution for UdaPeople.

Parameters:
  ID:
    Description: Unique identifier.
    Type: String
    Default: "67k9i1f1"
  WorkflowID:
    Description: WorkflowID
    Type: String

Resources:
  CloudFrontOriginAccessIdentity:
    Type: "AWS::CloudFront::CloudFrontOriginAccessIdentity"
    Properties:
      CloudFrontOriginAccessIdentityConfig:
        Comment: Origin Access Identity for Serverless Static Website

  WebpageCDN:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        Origins:
          - DomainName: !Sub "udapeople-${CIRCLE_WORKFLOW_ID:0:7}.s3.amazonaws.com"
            Id: webpage
            S3OriginConfig:
              OriginAccessIdentity: !Sub "origin-access-identity/cloudfront/${CloudFrontOriginAccessIdentity}"
        Enabled: True
        DefaultRootObject: index.html
        DefaultCacheBehavior:
          ForwardedValues:
            QueryString: False
          TargetOriginId: webpage
          ViewerProtocolPolicy: allow-all

Outputs:
  CloudFrontURL:
    Value: !Sub "udapeople-${CIRCLE_WORKFLOW_ID:0:7}.s3.amazonaws.com"
    Description: URL for website hosted on S3
    Export:
      Name: CloudFrontS3URL

  WorkflowID:
    Value: !Sub ${CIRCLE_WORKFLOW_ID:0:7}
    Description: WorkflowID
    Export:
      Name: WorkflowID
