version: 2.1

commands:
  destroy-environment:
    description: Destroy back-end and front-end cloudformation stacks given a workflow ID.
    parameters:
      workflow-id:
        type: string
        default: ${CIRCLE_WORKFLOW_ID:0:7}
    steps:
      - run:
          name: Destroy environments
          when: on_fail
          command: |
            aws s3 rm s3://udapeople-${CIRCLE_WORKFLOW_ID:0:7} --recursive 2> /dev/null
            aws cloudformation delete-stack --stack-name frontend-${CIRCLE_WORKFLOW_ID:0:7}
            aws cloudformation delete-stack --stack-name backend-${CIRCLE_WORKFLOW_ID:0:7}

  revert-migrations:
    description: Revert the last migration if successfully run in the current workflow.
    parameters:
    # Add parameter here     
    steps:
      - run:
          name: Revert migrations
          command: |
            curl -H "token: a69d49ff-fa6e-4f73-86ad-ae03427eb4eb" --request GET "https://api.memstash.io/values/Migration" > SUCCESS
            if(( $SUCCESS=="fail" ));
            then
              cd ~/project/backend
              npm install
              cat .env
              npm run migrations:revert
            fi

jobs:
  build-frontend:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout
      - restore_cache:
          keys: 
            - frontend-build-{{ .BuildNum }}
      - run:
          name: Build front-end
          command: |
            cd frontend
            npm install
            npm run build
            cd dist
            ls
      - save_cache:
          paths: [frontend/node_modules]
          key: frontend-build-{{ .BuildNum }}

  build-backend:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout
      - restore_cache:
          keys: 
            - backend-build-{{ .BuildNum }}
      - run:
          name: Back-end build
          command: |
            cd backend
            npm install
            npm run build
      - save_cache:
          paths: [backend/node_modules]
          key: backend-build-{{ .BuildNum }}

  test-frontend:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout
      - restore_cache:
          keys: 
            - frontend-build-{{ .BuildNum }}
      - run:
          name: Front-end test
          command: |
            cd frontend
            npm install
            npm run test

  test-backend:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout
      - restore_cache:
          keys: 
            - backend-build-{{ .BuildNum }}
      - run:
          name: Back-end test
          command: |
            cd backend
            npm install
            npm run test

  scan-frontend:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout
      - restore_cache:
          keys: 
            - frontend-build-{{ .BuildNum }}
      - run:
          name: Front-end scan
          command: |
            cd frontend
            npm install
            npm audit --audit-level=critical
  scan-backend:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout
      - restore_cache:
          keys: 
            - backend-build-{{ .BuildNum }}
      - run:
          name: Back-end scan
          command: |
            cd backend
            npm install
            npm audit --audit-level=critical

  deploy-infrastructure:
    docker:
      - image: amazon/aws-cli
    steps:
      - checkout
      - run:
          name: Install tar utility
          command: yum -y install tar gzip
      - run:
          name: Ensure back-end infrastructure exists
          command: |
            aws cloudformation deploy \
              --template-file .circleci/files/backend.yml \
              --tags project=proj4 \
              --tags name=backend \
              --stack-name "backend-${CIRCLE_WORKFLOW_ID:0:7}" \
              --region=us-west-2 \
              --parameter-overrides \
                ID="${CIRCLE_WORKFLOW_ID:0:7}" \
                VPCID="vpc-0caf7189e77171517" \
                EC2Subnet="subnet-0c2689f69a40847fd"
      - run:
          name: Ensure front-end infrastructure exist
          command: |
            aws cloudformation deploy \
              --template-file .circleci/files/frontend.yml \
              --tags project=proj4 \
              --stack-name "frontend-${CIRCLE_WORKFLOW_ID:0:7}" \
              --region=us-west-2
      - destroy-environment

  configure-infrastructure:
    docker:
      - image: python:3.7-alpine3.11
    steps:
      - checkout
      - add_ssh_keys:
          fingerprints: ["ee:90:b8:ab:8a:57:f1:36:9a:ea:20:5c:8d:ae:b6:e7"]
      - attach_workspace:
          at: ~/
      - run:
          name: Install dependencies
          command: |
            apk add --no-cache tar gzip
            apk add --update ansible npm nodejs curl
            pip install awscli 
      - run:
          name: Add back-end IP to ansible inventory
          command: |
            echo [web] > inventory.txt
            aws ec2 describe-instances \
              --region us-west-2 \
              --filters "Name=tag:project,Values=proj4" \
              --query 'Reservations[*].Instaces[*].[PublicIpAddress]' \
              --output text > BACKEND_IP
            $BACKEND_IP >> inventory.txt

            curl -H "Content-Type: text/plain" -H "token: a69d49ff-fa6e-4f73-86ad-ae03427eb4eb" --request PUT --data "$BACKEND_IP" https://api.memstash.io/values/backendIP
            curl -H "Content-Type: text/plain" -H "token: a69d49ff-fa6e-4f73-86ad-ae03427eb4eb" --request PUT --data "$inventory.txt" https://api.memstash.io/values/Inventory
            cd ~/project
            echo TYPEORM_CONNECTION=postgres >> "backend/.env"
            echo TYPEORM_ENTITIES=./src/modules/domain/**/*.entity.ts >> "backend/.env"
            echo TYPEORM_MIGRATIONS=./src/migrations/*.ts >> "backend/.env"
            echo TYPEORM_MIGRATIONS_DIR=./src/migrations >> "backend/.env"
            echo NODE_ENV=production >> "backend/.env"
            echo TYPEORM_HOST=$TYPEORM_HOST >> "backend/.env"
            echo TYPEORM_PORT=$TYPEORM_PORT >> "backend/.env"
            echo TYPEORM_USERNAME=$TYPEORM_USERNAME >> "backend/.env"
            echo TYPEORM_PASSWORD=$TYPEORM_PASSWORD >> "backend/.env"
            echo TYPEORM_DATABASE=$TYPEORM_DATABASE >> "backend/.env"          
            cd .circleci/ansible/
            ansible-playbook -i inventory.txt configure-server.yml
      - destroy-environment

  run-migrations:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout
      - restore_cache:
          keys: 
            - backend-build-{{ .BuildNum }}
      - run:
          name: install awscli and python
          command: |
            sudo apt-get -y -qq update
            sudo apt-get -y -qq install python3
            sudo apt-get -qq install awscli
      - run:
          name: Run migrations
          command: |
            sudo apt install curl
            cd ~/project/backend
            cat .env
            npm install
            npm run build
            npm run migrations > ~/project/backend/migration-status.txt
            echo "******migration status*****"
            echo migration-status.txt
      - run:
          name: Send migration results to memstash
          command: |
            cd ~/project/backend
            if grep -q "has been executed successfully" ~/project/backend/migration-status.txt
            then
              curl -H "Content-Type: text/plain" -H "token: a69d49ff-fa6e-4f73-86ad-ae03427eb4eb" --request PUT --data "success" https://api.memstash.io/values/Migration
              echo "**migration success**"
            else
              curl -H "Content-Type: text/plain" -H "token: a69d49ff-fa6e-4f73-86ad-ae03427eb4eb" --request PUT --data "fail" https://api.memstash.io/values/Migration
              echo "**migration fail**"
            fi
            echo "WorkflowID=${CIRCLE_WORKFLOW_ID:0:7}"
      - destroy-environment
      - revert-migrations

  deploy-frontend:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            sudo apt-get -y update
            sudo apt -y install curl
            sudo apt-get -y -qq install python3
            sudo apt-get -qq install awscli
      - run:
          name: Get backend url
          command: |
            aws ec2 describe-instances \
              --region us-west-2 \
              --filters "Name=tag:project,Values=proj4" \
              --query 'Reservations[*].Instaces[*].[PublicIpAddress]' \
              --output text > BACKEND_IP
            BACKEND_URL=http://$BACKEND_IP/latest/meta-data/public-hostname
            export API_URL="http://${BACKEND_URL}:3030"
            echo "***${API_URL}***"
            cd ~/project/frontend
            echo pwd
            npm install
            npm run build
      - run:
          name: Deploy frontend objects
          no_output_timeout: 10m
          command: |
            aws s3 cp ~/project/frontend/dist s3://newudapeople-67k9i1f1/ --recursive
      - destroy-environment
      - revert-migrations

  deploy-backend:
    docker:
      - image: python:3.7-alpine3.11
    steps:
      - checkout
      - add_ssh_keys:
          fingerprints: ["ee:90:b8:ab:8a:57:f1:36:9a:ea:20:5c:8d:ae:b6:e7"]
      - attach_workspace:
          at: ~/
      - run:
          name: Install dependencies
          command: |
            apk add --update ansible npm nodejs curl tar gzip
            pip install awscli
      - run:
          name: Deploy backend
          no_output_timeout: 10m
          command: |
            echo [web] > inventory.txt
            aws ec2 describe-instances \
              --region us-west-2 \
              --filters "Name=tag:project,Values=proj4" \
              --query 'Reservations[*].Instaces[*].[PublicIpAddress]' \
              --output text > BACKEND_IP
            cd .circleci/ansible
            $BACKEND_IP >> inventory.txt
            ansible-playbook -i inventory.txt deploy-backend.yml
      - destroy-environment
      - revert-migrations 

  smoke-test:
    docker:
      - image: python:3.7-alpine3.11
    steps:
      - checkout
      - run:
          name: Install dependancies
          command: |
            apk add curl tar gzip
            pip install awscli
      - attach_workspace:
          at: ~/
      - run:
          name: Frontend smoke test
          command: |
            URL=http://newudapeople-67k9i1f1.s3-website-us-west-2.amazonaws.com
            if $(curl -I ${URL} | grep "200 OK");
            then
              echo "Success Frontend smoke"
              return 0
            else
              echo "Fail Frontend smoke"
              return 1
            fi
      - run:
          name: Backend smoke test
          command: |
            aws ec2 describe-instances \
              --region us-west-2 \
              --filters "Name=tag:project,Values=proj4" \
              --query 'Reservations[*].Instaces[*].[PublicIpAddress]' \
              --output text > BACKEND_IP
            if $(curl -I http://${BACKEND_IP}:3030/api/status| grep "200 OK");
            then
              echo "Success backend smoke"
              return 0
            else
              echo "Fail backend smoke"
              return 1
      - destroy-environment
      - revert-migrations

  cloudfront-update:
    docker:
      # Docker image here that supports AWS CLI
      - image: amazon/aws-cli
    steps:
      # Checkout code from git
      - checkout
      - run:
          name: Install dependencies
          command: |
            yum -y install nodejs tar gzip
      - run:
          name: Update cloudfront distribution
          command: |
            aws cloudformation deploy \
              --template-file .circleci/files/cloudfront.yml \
              --stack-name udapeople-cloudfront \
              --parameter-overrides WorkflowID=${CIRCLE_WORKFLOW_ID:0:7} \
              --tags project=udapeople
      # Here's where you will add some code to rollback on failure
      - destroy-environment

  cleanup:
    docker:
      # Docker image here
      - image: amazon/aws-cli
    steps:
      # Checkout code from git
      - checkout
      - run:
          name: Get old stack workflow id
          command: |
            # your code here
            export OldWorkflowID=$(aws cloudformation list-exports \
                --query "Exports[?Name=='WorkflowID'].Value" \
                --region us-west-2 --no-paginate --output text)
            # Exporting stacks not required having the workflow ID
            export STACKS=export STACKS=$(aws cloudformation list-stacks --query "StackSummaries[*].StackName" \
                --stack-status-filter CREATE_COMPLETE --no-paginate --output text)
      - run:
          name: Remove old stacks and files
          command: |
            if [[ "${STACKS[@]}" =~ "${OldWorkflowID}" ]]
            then
              # your code here
              aws cloudformation delete-stack --stack-name frontend-${OldWorkflowID}
              aws cloudformation delete-stack --stack-name backend-${OldWorkflowID}
              aws s3 rb s3://udapeople-${OldWorkflowID} --force
            fi

workflows:
  default:
    jobs:
      - build-frontend
      - build-backend
      - test-frontend:
          requires: [build-frontend]
      - test-backend:
          requires: [build-backend]
      - scan-backend:
          requires: [build-backend]
      - scan-frontend:
          requires: [build-frontend]
      - deploy-infrastructure:
          requires: [test-frontend, test-backend, scan-frontend, scan-backend]
      - configure-infrastructure:
          requires: [deploy-infrastructure]
          filters:
            branches:
              only: [master]
      - run-migrations:
          requires: [configure-infrastructure]
      - deploy-frontend:
          requires: [run-migrations]
      - deploy-backend:
          requires: [run-migrations]
      - smoke-test:
          requires: [deploy-backend, deploy-frontend]
#      - cloudfront-update:
#          requires: [smoke-test]
#      - cleanup:
#          requires: [cloudfront-update]
